### ISSUE TITLE
Extensions Bug

### ISSUE THREAD

**Issue by Drybaby** [Spec-ify/specified#10]
Extensions here :
https://spec-ify.com/profile/c3f1a83e

Do not show at all.

Figure out.

**Comment by K97i** [comment]
I already explained in the thread, but I'm also going to put it here for completeness.

In the raw JSON, one of Chrome's listed extensions is Ghostery. The name contains an invalid character. Explained by VS Code: 

![Image](https://user-images.githubusercontent.com/105120272/214505919-2ec1545a-2e75-4629-a33b-2cdba9f20db9.png)

This causes the rest of the tables in the extensions tab to not work. Yes. One character in one entry caused this.

**Comment by K97i** [comment]
[c3f1a83e json.zip](https://github.com/Spec-ify/specified/files/10501470/c3f1a83e.json.zip)

**Comment by sealsrock12** [comment]
Fixed in https://github.com/Spec-ify/specified/commit/f3357474313bd7a8405475bcd9dfdbfa636130a0
