### ISSUE TITLE
Implement the x0.at file uploader to the server to handle minidump files

### ISSUE THREAD

**Issue by XavierNCline** [Spec-ify/specified#15]
Essentially make implement the file hosting PHP script used on x0.at from this repo: https://github.com/Rouji/single_php_filehost to handle minidump hosting. These should be paired with the JSON file being uploaded from the same client as well as conform to our 1 day data retention policy

**Comment by zleyyij** [comment]
## Todo
- Decide on a file path for everything. I currently like the idea of `./files/json` and `./files/zip`. This may break things as we change the path of the json.[ ]
- Deploy 0x to the url path of `/zipupload`
